# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a2b030bf5bd12bea5f1fe8416d3a8c69d99f59036617c223bfc7677b5b200dd8e5f22cf058af7d036f27a622d6b45a4d2eb39b2796c200c4496847b9ce0b872c

test:
  secret_key_base: 5d94d7835e16cc73736a168a3cb3b303adbedff04eef1d79db981099b0d54d4e810e2145644321e65cad4551697f0248efd729f0ae7444c1e1def74f078d13d1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
